### ISSUE TITLE
Doesn't working

### ISSUE THREAD

**Issue by KevinGong2013** [manuelkch/fastlane-plugin-code_push#2]
fastfile
```
    code_push_release_react(
                           app_name: "testapp",
                           deployment: "Production",
                           description: options[:desc],
                           target_binary_version: "~1.0.0",
                           )
```
output
```
[18:29:32]: $ code-push release-react testapp android -d Production --des "test" -m -t ~1.0.0 
[18:29:36]: ▸ [Error]  Unable to find or read "package.json" in the CWD. The "release-react" command must be executed in a React Native project folder.
```

**Comment by manuelkch** [comment]
@KevinGong2013 could you provide me with your relevant folder structure for debugging reason ?
I`ve something like 
- ./packag.json
- ./fastlane/Fastfile
and execute the fastlane command in the root directory of my react-native project where my package.json lives

**Comment by KevinGong2013** [comment]
@manuelkch sure

- ./package.json

- ./android/fastlane/Fastfile

execute `bundle exec fastlane android release version:x.y.z` in `./android` folder.

**Comment by manuelkch** [comment]
@KevinGong2013 thanks. The problem "is" that the code-push release-react command needs the package.json in the same folder where the execution tooks place.  I added an extra parameter to the action comand to be able to configure the execution dir of the command by yourself.

So in your case it should be something like this
`
code_push_release_react(
        execution_dir_path: "../",
        app_name: "YOURAPPNAME",
        ....
      )
`
See documentation https://github.com/manuelkch/fastlane-plugin-code_push#release-react-action

Update the plugin to v 0.2.0

**Comment by KevinGong2013** [comment]
thx.
